name: LiveWeather
version: 2.5.1
main: LiveWeather.Main
description: Allows player to experience live weather in the location they are at and live time, always seasonal

commands:
    liveweather:
        usage: /<command> [player]
        description: Toggles live weather.
    livetime:
        usage: /<command> [player]
        description: Toggles live time on and off.