name: LiveWeather
version: 2.2.5
main: LiveWeather.Main
description: Allows player to experience live weather in the location they are at and live time, always seasonal

commands:
    liveweather:
        usage: /<command> [fog] [player]
        description: Toggles live weather or fog on and off. Turning weather off turns fog off.
    livetime:
        usage: /<command> [player]
        description: Toggles live time on and off